### ISSUE TITLE
Bug report #1

### ISSUE THREAD

**Issue by biunang** [ziap/infinite-minesweeper#3]
bugs:
- lose focus when moving cursor out of the game, causing it to get stuck at dragging mode
- not able to differentiate between flag mode on pc until the cursor is away
- abnormal zoom scaling on pc

possible fixes:
- remove dragging state once out of focus
- revert back to the original state when hover on the activated state
- reduce scaling by approximately 5 times

**Comment by ziap** [comment]
1. is duplicate of #1

**Comment by ziap** [comment]
Current solution
- [x] Remove dragging state once out of focus
- [x] Use different hover color to differentiate
- [x] Fixed the scaling and also make it scale to cursor
